[package]
name = "cora"
version = "0.1.0"
authors = ["geekymoose <constantin.masson@umontreal.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
